#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Starter Kit: Weather Station Demo
Copyright (C) 2013 Olaf Lüke <olaf@tinkerforge.com>
Copyright (C) 2015 Matthias Bolte <matthias@tinkerforge.com>

starter_kit_weather_station_demo: Starter Kit: Weather Station Demo startup

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public
License along with this program; if not, write to the
Free Software Foundation, Inc., 59 Temple Place - Suite 330,
Boston, MA 02111-1307, USA.
"""

import sys

try:
    from starter_kit_weather_station_demo.main import main

    if __name__ == "__main__":
        main()
except ImportError:
    print('Could not import starter_kit_weather_station_demo. Please make sure that brickv is installed properly. ' + \
          'If you want to start brickv from source, you should direclty call "python main.py".')

    sys.exit(1)
