#!/bin/sh
set -e

if which py3clean >/dev/null 2>&1; then
	py3clean /usr/share/starter_kit_weather_station_demo 
else
	dpkg -L starter_kit_weather_station_demo | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi
